### ISSUE TITLE
docker anaconda3へのAlife環境インストールエラーにつきまして

### ISSUE THREAD

**Issue by xiaraix** [alifelab/alife_book_src#23]
お世話になります
Alifeのチュートリアルを参考にした環境構築で下記のようなエラーが出ます。
回避策ご教授いただけましたら幸いです。

docker pull continuumio/anaconda3
docker run -i -t continuumio/anaconda3 /bin/bash

git clone https://github.com/alifelab/alife_book_src.git

pip install pyglet pymunk vispy

cd alife_book_src
cd chap02
※ cd alife_book_src/chap02 とすると落ちました。

python game_of_life.py
以下エラーです。
Traceback (most recent call last):
  File "game_of_life.py", line 7, in <module>
    from alifebook_lib.visualizers import MatrixVisualizer
  File "../alifebook_lib/__init__.py", line 1, in <module>
    import vispy
ModuleNotFoundError: No module named 'vispy'

**Comment by maru-n** [comment]
@xiaraix 
ご報告ありがとうございます。ご迷惑をおかけして申し訳ありません。
docker環境での問題に関しまして、現在調査をおこなっております。

とりいそぎ、以下の確認をしていただけると、大変助かります。

1. vispyのインストールに関して
No module named 'vispy'とエラーが出ていますが、vispyモジュールのインストールは問題なく完了していますでしょうか？

```shell
$ pip install vispy
```
の実行で何かエラーが出ていましたら、そちらをいただけますか。

2. 環境に関して
vispyが問題なく入っていましたら、以下のページの2番の実行結果をいただけますか。
https://github.com/alifelab/alife_book_src/wiki/%E3%83%90%E3%82%B0%E5%A0%B1%E5%91%8A

よろしくお願いいたします。

**Comment by xiaraix** [comment]
@maru-n 様
レスありがとうございます。
1.
$ pip install vispy

Requirement already satisfied: numpy in /opt/conda/lib/python3.6/site-packages (from vispy) (1.14.3)
Building wheels for collected packages: vispy
  Running setup.py bdist_wheel for vispy ... done
  Stored in directory: /root/.cache/pip/wheels/78/4a/81/db541db6561a36f679953cc76037a743923e9862ab5516d227
Successfully built vispy
distributed 1.21.8 requires msgpack, which is not installed.
Installing collected packages: vispy
Successfully installed vispy-0.5.3

インストールは成功していると表示されているようなのですが、
pythonを実行すると
>>>import vispy
で下記のエラーが帰ってきています。
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/opt/conda/lib/python3.6/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/opt/conda/lib/python3.6/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/opt/conda/lib/python3.6/site-packages/vispy/util/fonts/_triage.py", line 11, in <module>
    from ._freetype import _load_glyph
  File "/opt/conda/lib/python3.6/site-packages/vispy/util/fonts/_freetype.py", line 16, in <module>
    from ...ext.fontconfig import find_font
  File "/opt/conda/lib/python3.6/site-packages/vispy/ext/fontconfig.py", line 12, in <module>
    raise ImportError('fontconfig not found')
ImportError: fontconfig not found

2.
python -c "import vispy; print(vispy.sys_info())"
インストールがうまく出来ていません
エラー表示
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'vispy'


ご検証の程、よろしくお願いいたします。

**Comment by maru-n** [comment]
@xiaraix 
ご連絡ありがとうございます。
当方のubuntu16.04環境で、continuumio/anaconda3のdockerイメージを利用した実行が出来ましたので、方法をご連絡します。

以下を試して頂ければと思います。

```shell
$ git clone https://github.com/alifelab/alife_book_src.git
$ docker pull continuumio/anaconda3
$ xhost local:
$ docker run -it -v ~/alife_book_src:/alife_book_src -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY continuumio/anaconda3 
# ~/alife_book_srcの部分はcloneしたpathに読み替える。もしくは、コンテナ内でclone
(docker)$ apt update
(docker)$ apt install python3-pyqt5 gcc -y
(docker)$ pip install vispy keras tensorflow pymunk pyglet
(docker)$ cd alife_book_src/chap02/
(docker)$ python game_of_life.py
```

**Comment by xiaraix** [comment]
maru-n 様

ご対応ありがとうございます。
各種インストール後、
python game_of_life.py
を実行すると以下のエラーが出ます。

UserWarning: VisPy is not yet compatible with matplotlib 2.2+
warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")

matplotlib のバージョンを2.1.0 に落としてインストール。
pip install matplotlib==2.1.0

上記インストール後、次のエラーが出ております。

WARNING: could not determine DPI
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
WARNING: Unrecognized OpenGL version
WARNING: Unrecognized OpenGL version

ご検証いただけますでしょうか。
